### ISSUE TITLE
'Dominance' object has no attribute 'incrimental_r2' / 'Dominance' object has no attribute 'variable_stats'

### ISSUE THREAD

**Issue by DaveDarrel** [dominance-analysis/dominance-analysis#13]
**Describe the bug**
Pretty simple, just trying to reproduce the examples and it seems that they are serious problem with the dominance.py:

from dominance_analysis import Dominance
dominance_regression = Dominance(data=X_train, target='TARGET', objective=1)

dominance_regression.plot_incremental_rsquare()
 --> 'Dominance' object has no attribute 'incrimental_r2'
dominance_regression.dominance_stats()
--> 'Dominance' object has no attribute 'variable_stats'

Did Nothing special, just pip install dominance-analysis, and tried it for the first time and here the results.

Hope it can be corrected because package seems great!!!

Thanks!!

**Comment by DaveDarrel** [comment]
Sorry, missing one line:

from dominance_analysis import Dominance
dominance_regression = Dominance(data=X_train, target='TARGET', objective=1)

dominance_regression.plot_incremental_rsquare()
 --> 'Dominance' object has no attribute 'incrimental_r2'
 dominance_regression.dominance_stats()
 --> 'Dominance' object has no attribute 'variable_stats'

**Comment by dominance-analysis** [comment]
Hi Dave –

Thanks for trying the library!
Please run the code in below order
 
from dominance_analysis import Dominance
dominance_regression = Dominance(data=X_train, target='TARGET', objective=1)
dominance_regression.incremental_rsquare()
 
After this step plot_incremental_rsquare() and dominance_stats() will work as all the statistics is being generated in the incremental_rsquare() function
 
Please try running the code in the stated sequence and let us know if any query and we will close this issue accordingly.

Thanks!

**Comment by dominance-analysis** [comment]
Closing this as the user missed one line in the code. The library is working as expected.

**Comment by DaveDarrel** [comment]
Yes it works!! 

Thanks you!
