### ISSUE TITLE
ValueError: Input X must be non-negative.

### ISSUE THREAD

**Issue by mileta1976** [dominance-analysis/dominance-analysis#14]
Thank you for this package.

If dataset has negative values in columns I get this is error: 
"ValueError: Input X must be non-negative."

Dataset example: https://www.kaggle.com/c/instant-gratification

Tnx

P.S. For this dataset https://www.kaggle.com/c/instant-gratification
dominance analysis did not recognize feature "wheezy-copper-turtle-magic" as important
(categorical variable encoded as integer)
https://www.kaggle.com/c/instant-gratification/discussion/92587

**Comment by dominance-analysis** [comment]
Hi,

Thanks a lot for trying out our library and bringing this issue to our notice.

The mentioned data set had negative values and the Chi Square test for picking the top features was failing. We have updated the library to handle such cases now.  I am hence closing this issue.

If any further problems are faced, please let us know.

Thanks !
