### ISSUE TITLE
Attribute Error when calling dominance_stats()

### ISSUE THREAD

**Issue by gvasilakop** [dominance-analysis/dominance-analysis#15]
Getting an AttributeError: 'Dominance' object has no attribute 'variable_stats' when trying to call that method.

Replicate it by running the breast cancer example found in the documentation.

**Comment by bhagatsajan0073** [comment]
Hi gvasilakop –

Thanks for trying the library!
We have resolved the issue in latest update. Please upgrade the package once and let us know if it is working for you.

Thanks
