### ISSUE TITLE
Dominance relative percentage as negative

### ISSUE THREAD

**Issue by flappy007** [dominance-analysis/dominance-analysis#16]
I ran dominance analysis with a set of data and getting negative total dominance values as well as negative percentage. Though the percentage adds up to 100 but shouldn't the percentage be positive numbers.
Adding the data used and results as well.

df = pd.read_excel('data.xlxs', sheet_name='data')
df_regression = Dominance(data=df, target='score', objective=1)
df_regression.incremental_rsquare()
df_tda = df_regression.dominance_stats()['Percentage Relative Importance']

[data_results.xlsx](https://github.com/dominance-analysis/dominance-analysis/files/4661765/data_results.xlsx)

**Comment by bhagatsajan0073** [comment]
Hi flappy007,

Thanks for trying dominance-analysis. I have checked the dominance-analysis for provided data and it's working fine for me. 

Please find the link below to kaggle kernel that i created on your data for your convenience 

https://www.kaggle.com/iamsajanbhagat/dominance-relative-percentage-as-negative


Thanks & Regards
Sajan Kumar

**Comment by bhagatsajan0073** [comment]
Hi flappy007,

Closing this issue!
Please reopen it if you still face the issue

Thanks
Sajan Kumar
