### ISSUE TITLE
Only the last plot is showing up for incremental_rsquare()

### ISSUE THREAD

**Issue by teresadong** [dominance-analysis/dominance-analysis#17]
**Describe the bug**
I can only get the last plot to show up for the dominance_regression.plot_incremental_rsquare() function.

**To Reproduce**
I followed the tutorial in order.
1. Import Libaries
from dominance_analysis import Dominance_Datasets
from dominance_analysis import Dominance

2. Import Toy Data
boston_dataset=Dominance_Datasets.get_boston()

3. Run Regression
dominance_regression=Dominance(data=boston_dataset,target='House_Price',objective=1)

4. Get RSquared
incr_variable_rsquare=dominance_regression.incremental_rsquare()

5. Plot the Incremental R-Squared
dominance_regression.plot_incremental_rsquare()

**Expected behavior**

I expected all the plots to show up but only the last plot is visible

**Screenshots**
![missing_plots](https://user-images.githubusercontent.com/3849181/93641324-efbe2e00-f9b0-11ea-89ab-95b0fa612217.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version: 85.0.4183.83

**Additional context**

**Comment by bhagatsajan0073** [comment]
Hi teresadong,

This is a known issue that comes because of the underlying Plotly package for now restarting the kernel will resolve the issue.

Thanks
Sajan
