### ISSUE TITLE
scipy=1.2.1 is used (scipy.misc is now depreciated)

### ISSUE THREAD

**Issue by siddhant-swaroop-dash** [dominance-analysis/dominance-analysis#18]
**Describe the bug**
unable to install with dependencies

**To Reproduce**
pip install dominance_analysis

**Expected behavior**
should be installed with dependencies

**Comment by siddhant-swaroop-dash** [comment]
was able to install using setup.py
but still depreciated functions are used

**Comment by bhagatsajan0073** [comment]
Hi Siddhant -

We will update the same in the next planned build. Thanks for pointing the issue.

Regards
Sajan

**Comment by Robin0105** [comment]
> was able to install using setup.py
> but still depreciated functions are used

Can i ask how you went about it?
