### ISSUE TITLE
R Squared more than 1

### ISSUE THREAD

**Issue by flappy007** [dominance-analysis/dominance-analysis#19]
Hi Team,

I am getting more than 1 for R-Squared value for the attached data.

[test.xlsx](https://github.com/dominance-analysis/dominance-analysis/files/5401492/test.xlsx)

**code used:**

import pandas as pd
from dominance_analysis import Dominance

dfA = pd.read_excel(r"test.xlsx")
dfA_corr = dfA.corr()
#dfA_regression = Dominance(data=dfA, target="ltr", objective=1)
dfA_regression = Dominance(data=dfA_corr, target="ltr", data_format=1)
R2_value = dfA_regression.complete_model_rsquare()

The reason for using correlation method is because we do not want to remove the any nulls from data. The last record has BU as null. If we use objective=1, then we need to remove all null rows, we do not intend to remove it.

Please suggest.

**Comment by bhagatsajan0073** [comment]
Hi @flappy007 

R-Squared is coming more than 1 when you are not handling null values in data. 

I tried multiple methods of missing value imputation(Mean, Median, Mode, and Custom) on data provided by you and I'm getting R-square in an acceptable range. Please refer to the markdown file for your reference.

[Issues Resolution.md](https://github.com/dominance-analysis/dominance-analysis/files/6668086/Issues.Resolution.md)
