### ISSUE TITLE
How to use for Logistic Regression

### ISSUE THREAD

**Issue by arainboldt** [dominance-analysis/dominance-analysis#22]
Hi all! 

Very interesting package and oddly unique in the python ecosystem. I really appreciate your work here. 

I'm just starting to explore DA and RWA as method of driver analysis, and so trying to better understand how things work generally and how to use the `driver-analysis` package specifically. 

A problem I'm currently working on is setup as a logistic regression problem, and reading through the code, I see that if `objective` is set to 1 the `r-sq` values are estimated via a linear regression model while otherwise it uses the indicated r-sq method, e.g. `mcfadden`.  

I also noticed that the `LogisticRegression` class has been imported from sklearn but isn't used. I found this odd, and consequently, am wondering if in the case of logistic regression, one should set `objective` to 0 or if it's just not implemented yet. 

What's the recommended usage here?

Thanks!

Andrew

**Comment by arainboldt** [comment]
After some further exploration I see that the `stats_models.Logit` model is used to estimate the `r-sq` for the additional methods, so it looks like this is what is intended for the LogReg use case. Let me know if I've misunderstood something

**Comment by quintshekhar** [comment]
You can use Pseudo R squared for Logistic Regression!
