### ISSUE TITLE
Working with large datasets

### ISSUE THREAD

**Issue by arainboldt** [dominance-analysis/dominance-analysis#23]
**Is your feature request related to a problem? Please describe.**

Due to the combinatorial explosion in the number of models necessary to evaluate dominance of `n` features in a dataset, it's not feasible to evaluate a dataset with more than ~15 features. 

Currently, it appears that the only implemented feature available for dealing with this difficulty is the argument `top-k` which selects the `k` most `dominant` features and evaluates all models on these, to the exclusion of the rest. 

This is helpful, but makes it difficult to compare features from a larger dataset as it excludes all additional features.

Would it be possible to justify calculating the dominance using a sub-sample of the model space `M` using only `m` models where `m` is equal to the (N,r) combinations where `r` is set to a max value, e.g. 4, while `N` remains equal to the total number of features in the original dataset instead of being truncated prematurely at e.g. 15. In other words, the feature combinations would be all tetraplets, triplets, pairs, and singles from the entire feature space, if `r` == 4.

This sampling technique is similar to the balanced incomplete block design structure of best-worst scaling analysis. I haven't yet investigated, but perhaps the BWS literature can provide some direction on the mathematical foundations of such an approach. 

Not sure if this repo is still active, but would love to hear ideas and feedback from the authors on the idea given their familiarity and expertise with the package and dominance analysis in general. 

Best,

Andrew

**Comment by quintshekhar** [comment]
This is a legit suggestion and we can definitely explore this. We will try getting this in our next release. We can use a variant of Lucas thorem to build the base of the approach.
