### ISSUE TITLE
Is this librarray still maintained ? Can we help ?

### ISSUE THREAD

**Issue by jxraynaud** [dominance-analysis/dominance-analysis#26]
I'd like to know if there are still some active contributors on this package ?
We would like to use it, but noticed that there wasn't much activity here.

We also weren't able to make it run on Python 3.8, 3.10 and 3.6. On 3.7 it seems to run, but that's rather limited.

We can help with the maintenance part of this package, the first steps would be to:

- Use Tox to test on various environments if the library is correctly installed.
- Add some unit tests to the library.
- Make it run on 3.7+ instead of just 3.1

Let us know if you're interested.

Thanks !

**Comment by sajanbhagat** [comment]
@jxraynaud we have tested dominance analysis and it works on python 3.8 and below version. Do let me know what exact issue you are facing on the version below python 3.9. for the version above python 3.8, there is a dependency issue b/w python and a minimum NumPy version supported, which in terms creates an issue with the Scipy version that we are using in the package. We are looking forward to making it work but for time being we will be able to support python 3.8 and below version only.

Looking forward to your detailed issue with the version, we will help you to make it work.

Thanks
Sajan Kumar

**Comment by nhathpham1** [comment]
@sajanbhagat Hi Sajan! Do you have any recommendations why I can try to make it work for python 3.9? I'm very interested in using the package but will not be able to downgrade it to 3.8.

Thank you!

**Comment by sajanbhagat** [comment]
Please test the latest version and let me know if everything working fine or not
